# Programming with Python

## Episode 1a - Introduction - Analysing Patient Data

Teaching: 60 min, 
Exercises: 30 min 


Objectives
 
- Assign values to variables.

- Explain what a library is and what libraries are used for.

- Import a Python library and use the functions it contains.

- Read tabular data from a file into a program.

- Select individual values and subsections from data.

- Perform operations on arrays of data.

## Our Dataset
In this episode we will learn how to work with CSV files in Python. Our dataset contains patient inflammation data - where each row represents a different patient and the column represent inflammation data over a series of days. 

![Data Files](data/inflammation-excel.png)


However, before we discuss how to deal with many data points, let's learn how to work with single data values.



## Variables
Any Python interpreter can be used as a calculator:

```
3 + 5 * 4
```

In [1]:
3 + 5 * 4

23

This is great but not very interesting. To do anything useful with data, we need to assign its value to a variable. In Python, we can assign a value to a variable, using the equals sign ``=``. For example, to assign value 60 to a variable ``weight_kg``, we would execute:

```
weight_kg = 60
```

In [6]:
kellys_weight = 40

From now on, whenever we use ``weight_kg``, Python will substitute the value we assigned to it. In essence, a variable is just a name for a value.

```
weight_kg + 5
```

In [7]:
kellys_weight + 4

44

In Python, variable names:

- can include letters, digits, and underscores - `A-z, a-z, _`
- cannot start with a digit
- are case sensitive.

This means that, for example:

`weight0` is a valid variable name, whereas `0weight` is not
`weight` and `Weight` are different variables

#### Types of data
Python knows various types of data. Three common ones are:

- integer numbers (whole numbers)
- floating point numbers (numbers with a decimal point)
- and strings (of characters).

In the example above, variable `weight_kg` has an integer value of `60`. To create a variable with a floating point value, we can execute:

```
weight_kg = 60.0
```

In [8]:
kellys_weight = 50.0

And to create a string we simply have to add single or double quotes around some text, for example:

```
weight_kg_text = 'weight in kilograms:'
```

To display the value of a variable to the screen in Python, we can use the print function:

```
print(weight_kg)
```

In [9]:
kellys_kg_text = 'weight in kilograms'
print (kellys_weight)

50.0


We can display multiple things at once using only one print command:

```
print(weight_kg_text, weight_kg)
```

In [10]:
print(kellys_kg_text,kellys_weight)

weight in kilograms 50.0


Moreover, we can do arithmetic with variables right inside the print function:

```
print('weight in pounds:', 2.2 * weight_kg)
```

The above command, however, did not change the value of ``weight_kg``:

```
print(weight_kg)
```

In [12]:
print(kellys_weight)

50.0


To change the value of the ``weight_kg`` variable, we have to assign `weight_kg` a new value using the equals `=` sign:

```
weight_kg = 65.0
print('weight in kilograms is now:', weight_kg)
```

In [13]:
weight_kg=65
print('weight in kilograms is now:', weight_kg)

weight in kilograms is now: 65


#### Variables as Sticky Notes

A variable is analogous to a sticky note with a name written on it: assigning a value to a variable is like writing a value on the sticky note with a particular name.

This means that assigning a value to one variable does not change values of other variables (or sticky notes). For example, let's store the subject's weight in pounds in its own variable:

```
# There are 2.2 pounds per kilogram
weight_lb = 2.2 * weight_kg
print(weight_kg_text, weight_kg, 'and in pounds:', weight_lb)
```

In [16]:
#2.2 pounds per kilograms
weight_lb=2.2*weight_kg
print('weight_kg_text',weight_kg,'and in pounds:', weight_lb)

weight_kg_text 65 and in pounds: 143.0


#### Updating a Variable

Variables calculated from other variables do not change their value just because the original variable changed its value (unlike cells in Excel):

```
weight_kg = 100.0
print('weight in kilograms is now:', weight_kg, 'and weight in pounds is still:', weight_lb)
```

In [17]:
weight_kg=100
print('weight in kilograms is now:', weight_kg, 'and weight in pounds is still:', weight_lb)

weight in kilograms is now: 100 and weight in pounds is still: 143.0


Since `weight_lb` doesn't *remember* where its value comes from, so it is not updated when we change `weight_kg`.

## Libraries

Words are useful, but what's more useful are the sentences and stories we build with them (or indeed entire books or whole libraries). Similarly, while a lot of powerful, general tools are built into Python, specialised tools built up from these basic units live in *libraries* that can be called upon when needed.

### Loading data into Python

In order to load our inflammation dataset into Python, we need to access (import in Python terminology) a library called `NumPy` (which stands for Numerical Python). 

In general you should use this library if you want to do fancy things with numbers, especially if you have matrices or arrays. We can import `NumPy` using:

```
import numpy
```

In [ ]:
import numpy

Importing a library is like getting a piece of lab equipment out of a storage locker and setting it up on the bench. Libraries provide additional functionality to the basic Python package, much like a new piece of equipment adds functionality to a lab space. Just like in the lab, importing too many libraries can sometimes complicate and slow down your programs - so we only import what we need for each program. Once we've imported the library, we can ask the library to read our data file for us:

```
numpy.loadtxt(fname='data/inflammation-01.csv', delimiter=',')
```

The expression `numpy.loadtxt(...)` is a function call that asks Python to run the function `loadtxt` which belongs to the `numpy` library. This dot `.` notation is used everywhere in Python: the thing that appears before the dot contains the thing that appears after.

As an example, John Smith is the John that belongs to the Smith family. We could use the dot notation to write his name smith.john, just as `loadtxt` is a function that belongs to the `numpy` library.

`numpy.loadtxt` has two parameters: the name of the file we want to read and the delimiter that separates values on a line. These both need to be character strings (or strings for short), so we put them in quotes.

Since we haven't told it to do anything else with the function's output, the notebook displays it. In this case, that output is the data we just loaded. By default, only a few rows and columns are shown (with ... to omit elements when displaying big arrays). To save space, Python displays numbers as 1. instead of 1.0 when there's nothing interesting after the decimal point.

Our call to `numpy.loadtxt` read our file but didn't save the data in memory. To do that, we need to assign the array to a variable. Just as we can assign a single value to a variable, we can also assign an array of values to a variable using the same syntax. Let's re-run `numpy.loadtxt` and save the returned data:

```
data = numpy.loadtxt(fname='data/inflammation-01.csv', delimiter=',')
```

In [27]:
numpy.loadtxt(fname='data/inflammation-01.csv',delimiter=',')

array([[0., 0., 1., ..., 3., 0., 0.],
       [0., 1., 2., ..., 1., 0., 1.],
       [0., 1., 1., ..., 2., 1., 1.],
       ...,
       [0., 1., 1., ..., 1., 1., 1.],
       [0., 0., 0., ..., 0., 2., 0.],
       [0., 0., 1., ..., 1., 1., 0.]])

In [26]:
import numpy
data=numpy.loadtxt(fname='data/inflammation-01.csv',delimiter=',')
print(data)

[[0. 0. 1. ... 3. 0. 0.]
 [0. 1. 2. ... 1. 0. 1.]
 [0. 1. 1. ... 2. 1. 1.]
 ...
 [0. 1. 1. ... 1. 1. 1.]
 [0. 0. 0. ... 0. 2. 0.]
 [0. 0. 1. ... 1. 1. 0.]]


This statement doesn't produce any output because we've assigned the output to the variable `data`. If we want to check that the data has been loaded, we can print the variable's value:

```
print(data)
```

In [ ]:
print(data)

Now that the data is in memory, we can manipulate it. First, let's ask Python what type of thing `data` refers to:

```
print(type(data))
```

In [28]:
print(type(data))

<class 'numpy.ndarray'>


The output tells us that data currently refers to an N-dimensional array, the functionality for which is provided by the `NumPy` library. This data correspond to arthritis patients' inflammation. The rows are the individual patients, and the columns are their daily inflammation measurements.

#### Data Type

A NumPy array contains one or more elements of the same type. The type function will only tell you that a variable is a NumPy array but won't tell you the type of thing inside the array. We can find out the type of the data contained in the NumPy array.

```
print(data.dtype)
```

In [30]:
print(data.dtype)

float64


This tells us that the NumPy array's elements are floating-point numbers.

With the following command, we can see the array's shape:

```
print(data.shape)
```

In [31]:
print(data.shape)

(60, 40)


The output tells us that the data array variable contains 60 rows and 40 columns. When we created the variable data to store our arthritis data, we didn't just create the array; we also created information about the array, called members or attributes. This extra information describes data in the same way an adjective describes a noun. data.shape is an attribute of data which describes the dimensions of data. We use the same dotted notation for the attributes of variables that we use for the functions in libraries because they have the same part-and-whole relationship.

If we want to get a single number from the array, we must provide an index in square brackets after the variable name, just as we do in math when referring to an element of a matrix. Our inflammation data has two dimensions, so we will need to use two indices to refer to one specific value:

```
print('first value in data:', data[0, 0])
print('middle value in data:', data[30, 20])
```

In [32]:
print('first value in data:',data[0,0])
print('middle value in data:',data[30,20])

first value in data: 0.0
middle value in data: 13.0


The expression `data[30, 20]` accesses the element at row 30, column 20. While this expression may not surprise you, `data[0, 0]` might. 

#### Zero Indexing

Programming languages like Fortran, MATLAB and R start counting at 1 because that's what human beings have done for thousands of years. Languages in the C family (including C++, Java, Perl, and Python) count from 0 because it represents an offset from the first value in the array (the second value is offset by one index from the first value). This is closer to the way that computers represent arrays (if you are interested in the historical reasons behind counting indices from zero, you can read Mike Hoye's blog post). 

As a result, if we have an M×N array in Python, its indices go from 0 to M-1 on the first axis and 0 to N-1 on the second. It takes a bit of getting used to, but one way to remember the rule is that the index is how many steps we have to take from the start to get the item we want.

#### In the Corner

What may also surprise you is that when Python displays an array, it shows the element with index `[0, 0]` in the upper left corner rather than the lower left. This is consistent with the way mathematicians draw matrices but different from the Cartesian coordinates. The indices are (row, column) instead of (column, row) for the same reason, which can be confusing when plotting data.

#### Slicing data

An index like `[30, 20]` selects a single element of an array, but we can select whole sections as well. For example, we can select the first ten days (columns) of values for the first four patients (rows) like this:

```
print(data[0:4, 0:10])
```

In [33]:
print(data[0:4,0:10])

[[0. 0. 1. 3. 1. 2. 4. 7. 8. 3.]
 [0. 1. 2. 1. 2. 1. 3. 2. 2. 6.]
 [0. 1. 1. 3. 3. 2. 6. 2. 5. 9.]
 [0. 0. 2. 0. 4. 2. 2. 1. 6. 7.]]


The slice `[0:4]` means, *Start at index 0 and go up to, but not including, index 4*. 

Again, the up-to-but-not-including takes a bit of getting used to, but the rule is that the difference between the upper and lower bounds is the number of values in the slice.

Also, we don't have to start slices at `0`:

```
print(data[5:10, 0:10])
```

In [34]:
print(data[5:10,0:10])

[[0. 0. 1. 2. 2. 4. 2. 1. 6. 4.]
 [0. 0. 2. 2. 4. 2. 2. 5. 5. 8.]
 [0. 0. 1. 2. 3. 1. 2. 3. 5. 3.]
 [0. 0. 0. 3. 1. 5. 6. 5. 5. 8.]
 [0. 1. 1. 2. 1. 3. 5. 3. 5. 8.]]


and we don't have to include the upper or lower bound on the slice. 

If we don't include the lower bound, Python uses 0 by default; if we don't include the upper, the slice runs to the end of the axis, and if we don't include either (i.e., if we just use `:` on its own), the slice includes everything:

```
small = data[:3, 36:]
print('small is:')
print(small)
```

In [36]:
small=data[:3,36:]
print('small is:')
print(small)

small is:
[[2. 3. 0. 0.]
 [1. 1. 0. 1.]
 [2. 2. 1. 1.]]


The above example selects rows 0 through 2 and columns 36 through to the end of the array.

thus small is:
```
[[ 2.  3.  0.  0.]
 [ 1.  1.  0.  1.]
 [ 2.  2.  1.  1.]]
```

Arrays also know how to perform common mathematical operations on their values. The simplest operations with data are arithmetic: addition, subtraction, multiplication, and division. When you do such operations on arrays, the operation is done element-by-element. Thus:

```
doubledata = data * 2.0
```

In [37]:
doubledata=data*2.0

will create a new array doubledata each element of which is twice the value of the corresponding element in data:

```
print('original:')
print(data[:3, 36:])
print('doubledata:')
print(doubledata[:3, 36:])
```

In [38]:
print('original:')
print(data[:3,36:])
print('doubledata:')
print(doubledata[:3,36:])

original:
[[2. 3. 0. 0.]
 [1. 1. 0. 1.]
 [2. 2. 1. 1.]]
doubledata:
[[4. 6. 0. 0.]
 [2. 2. 0. 2.]
 [4. 4. 2. 2.]]


If, instead of taking an array and doing arithmetic with a single value (as above), you did the arithmetic operation with another array of the same shape, the operation will be done on corresponding elements of the two arrays. Thus:

```
tripledata = doubledata + data
```

In [39]:
tripledata=doubledata+data

will give you an array where `tripledata[0,0]` will equal `doubledata[0,0]` plus `data[0,0]`, and so on for all other elements of the arrays.

```
print('tripledata:')
print(tripledata[:3, 36:])
```

In [40]:
print('tripledata:')
print(tripledata[:3,36:])

tripledata:
[[6. 9. 0. 0.]
 [3. 3. 0. 3.]
 [6. 6. 3. 3.]]


## Exercises

### Variables

What values do the variables mass and age have after each statement in the following program? 
```
mass = 47.5
age = 122
mass = mass * 2.0
age = age - 20
print(mass, age)
```
Test your answers by executing the commands.

In [41]:
mass=47.5
age=122
mass=mass*2
age=age-20
print(mass,age)

95.0 102


Solution:

### Sorting Out References

What does the following program print out?
```
first, second = 'Grace', 'Hopper'
third, fourth = second, first
print(third, fourth)
```

In [42]:
first,second='Grace','Hopper'
third,fourth=second,first
print(third,fourth)

Hopper Grace


Solution:

### Slicing Strings
A section of an array is called a slice. We can take slices of character strings as well:
```
element = 'oxygen'
print('first three characters:', element[0:3])
print('last three characters:', element[3:6])
```

What is the value of `element[:4]` ? What about `element[4:]`? Or `element[:]` ?

What about `element[-1]` and `element[-2]` ?

In [50]:
element='oxygen'
print('first three characters:',element[0:3])
print('last three characters:',element[3:6])
print('all?',element[:])
print('-2',element[-1])

first three characters: oxy
last three characters: gen
all? oxygen
-2 n


Solution:

Given those answers, explain what `element[1:-1]` does.

In [54]:
element[1:-1]

'xyge'

Solution: 

### Thin Slices

The expression `element[3:3]` produces an empty string, i.e., a string that contains no characters. If data holds our array of patient data, what does `data[3:3, 4:4]` produce? What about `data[3:3, :]` ?

In [72]:
print(data[3:4,:])

[[ 0.  0.  2.  0.  4.  2.  2.  1.  6.  7. 10.  7.  9. 13.  8.  8. 15. 10.
  10.  7. 17.  4.  4.  7.  6. 15.  6.  4.  9. 11.  3.  5.  6.  3.  3.  4.
   2.  3.  2.  1.]]


Solution:

## Key Points
Import a library into a program using import library_name.

Use the numpy library to work with arrays in Python.

Use `variable` `=` `value` to assign a value to a variable in order to record it in memory.

Variables are created on demand whenever a value is assigned to them.

Use `print(something)` to display the value of something.

The expression `array.shape` gives the shape of an array.

Use `array[x, y]` to select a single element from a 2D array.

Array indices start at 0, not 1.

Use `low:high` to specify a slice that includes the indices from low to high-1.

All the indexing and slicing that works on arrays also works on strings.

Use `#` and some kind of explanation to add comments to programs.

# Save, and version control your changes

- save your work: `File -> Save`
- add all your changes to your local repository: `Terminal -> git add .`
- commit your updates a new Git version:  `Terminal -> git commit -m "End of Episode 1"`
- push your latest commits to GitHub: `Terminal -> git push`